
[profile.default]
solc_version = '0.8.19'
evm_version = 'berlin'
auto_detect_solc = false
optimizer = true
optimizer_runs = 200 # Default amount
ffi = true
fuzz_runs = 1_000
remappings = [
    "forge-std=lib/forge-std/src/",
    "foundry-huff=lib/foundry-huff/src/",
    "@hack/=src/",
    "solmate/=lib/solmate/src/",
    "@openzeppelin/=lib/openzeppelin-contracts/contracts/token/",
    "@openzeppelinMath/=lib/openzeppelin-contracts/contracts/utils/",
    "@openzeppelinAccess/=lib/openzeppelin-contracts/contracts/access/"
]
fs_permissions = [
    { access = "read", path = "./test/erc721/wrapper.huff" }
]

[profile.default.fuzz]
runs = 1000
